
GET https://localhost:7136/users/77
X-API-KEY: Juventus

###

POST https://localhost:7136/users
Content-Type: application/json
X-API-KEY: Juventus


{
  "name": ""
}

###

PUT https://localhost:7136/users/1
Content-Type: application/json
X-API-KEY: Juventus


{
  "name": "Jane Doe"
}

###

DELETE https://localhost:7136/users/7
X-API-KEY: Juventus

###

GET https://localhost:7136/users
X-API-KEY: Juventus
